### ISSUE TITLE
user ERD

### ISSUE THREAD

**Issue by vibolkhan** [pnc-virtual-company/2022-G6-VC2-PART2#3]
Design attribute of user in database

**Comment by VichetMorm** [comment]
![Image](https://user-images.githubusercontent.com/90229555/189341609-427abf01-b46a-40b7-9497-de0cad98a3b7.png)

**Comment by vibolkhan** [comment]
keep only table that we use this week, relationship user and alumni is 1 to 1, and add more necessary field in table alumni

**Comment by VichetMorm** [comment]
![Image](https://user-images.githubusercontent.com/90229555/189475541-72dfec17-d128-4f59-a0c9-ad90690311f3.png)
