### ISSUE TITLE
update general information, update profile, and edite my work experience

### ISSUE THREAD

**Issue by vibolkhan** [pnc-virtual-company/2022-G6-VC2-PART2#5]
design mock up for alumni profile view

**Comment by OUN-BAV** [comment]
ALUMNI ACCOUNT

![Image](https://user-images.githubusercontent.com/92005233/189472442-dc69f043-65d2-4e05-a784-d24b4869c494.jpg)
![Image](https://user-images.githubusercontent.com/92005233/189472444-f927dcc2-5a47-4e74-91d8-06993f9f7f73.png)
![Image](https://user-images.githubusercontent.com/92005233/189472443-4e3f8bcb-7875-4910-ad02-0ece9ecdb49d.jpg)

**Comment by OUN-BAV** [comment]
ERO ACCOUNT

![Image](https://user-images.githubusercontent.com/92005233/189472568-7608c592-d2e8-4ada-b5ca-52749382e82a.png)
![Image](https://user-images.githubusercontent.com/92005233/189472569-ca564e50-211b-4fb9-8e8f-c31f41ff98c8.jpg)
